### ISSUE TITLE
Backend validation check fails during remote init 

### ISSUE THREAD

**Issue by atselikov** [KI-labs/kaos#91]
#### What is the current behaviour?

Backend validation check fails during remote init.

#### What is the expected behaviour?

For remote initialization backed validation should pass.

#### How to reproduce? (e.g. logs, minimal example, etc...)

`(kaos)  ✝  ~/work/kaos   master±  kaos init -e http://xxx.amazonaws.com:80/api/
`
> Token:
> Traceback (most recent call last):
>   File "/Users/alex/.local/share/virtualenvs/kaos-JyCdW911/bin/kaos", line 11, in <module>
>     load_entry_point('kaos', 'console_scripts', 'kaos')()
>   File "/Users/alex/work/kaos/cli/kaos_cli/main.py", line 8, in start
>     kaos(obj={})
>   File "/Users/alex/.local/share/virtualenvs/kaos-JyCdW911/lib/python3.7/site-packages/click/core.py", line 764, in __call__
>     return self.main(*args, **kwargs)
>   File "/Users/alex/.local/share/virtualenvs/kaos-JyCdW911/lib/python3.7/site-packages/click/core.py", line 717, in main
>     rv = self.invoke(ctx)
>   File "/Users/alex/.local/share/virtualenvs/kaos-JyCdW911/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/Users/alex/.local/share/virtualenvs/kaos-JyCdW911/lib/python3.7/site-packages/click/core.py", line 956, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/Users/alex/.local/share/virtualenvs/kaos-JyCdW911/lib/python3.7/site-packages/click/core.py", line 555, in invoke
>     return callback(*args, **kwargs)
>   File "/Users/alex/work/kaos/cli/kaos_cli/utils/decorators.py", line 22, in new_func
>     return ctx.invoke(f, obj, *args, **kwargs)
>   File "/Users/alex/.local/share/virtualenvs/kaos-JyCdW911/lib/python3.7/site-packages/click/core.py", line 555, in invoke
>     return callback(*args, **kwargs)
>   File "/Users/alex/work/kaos/cli/kaos_cli/commands/initialization.py", line 27, in init
>     elif backend.is_created():
> AttributeError: 'BackendFacade' object has no attribute 'is_created'
>

**Comment by ImScientist** [comment]
Can someone check this [pull request](https://github.com/KI-labs/kaos/pull/89)?
